version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  build:
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pylint
      - echo "Build started on `date`"
      - echo "Compiling the code"
      - echo "$CODEBUILD_SRC_DIR"
      
  post_build:
    commands:
      - export DJANGO_SETTINGS_MODULE=project.settings
      - python --version
      - pylint $CODEBUILD_SRC_DIR/*.py
      - echo "$CODEBUILD_SRC_DIR"
      - pylint --load-plugins pylint_django $CODEBUILD_SRC_DIR/project/urls.py

artifacts:
  files:
    - '**/*'